### PR TITLE
Create a single reusable data-repair command.

### PR DESCRIPTION
**Pull request by dralley**
[noissue]

### CODE REVIEW

**Comment by dralley** [comment]
@mdellweg @bmbouter  What do you think about this in principle?

**Comment by mdellweg** [comment]
I do not see much difference. The biggest impact is probably that `pulpcore-manager --help` will only show a single command instead of a whole list.

Design questions that come to my mind:
* Do/can we require all data repair to honor the `--dry-run` flag?
* Do plugins need to provide their own version of this command, or can the plug in?
* Should we identify the issue by `<app_label>:<nr>` or `<gh-repo>:<nr>?

**Comment by dralley** [comment]
>Do plugins need to provide their own version of this command, or can the plug in?

I was thinking plugins would provide their own.

> Do/can we require all data repair to honor the --dry-run flag?

I think we can probably strive to do that.  I'd be more concerned about the potential need for other flags.

>Should we identify the issue by <app_label>:<nr> or `:?

Since it would only be for pulpcore that's probably not necessary, but I suppose you're concerned about overlaps?

**Comment by dralley** [comment]
@mdellweg Should this proceed or should it just be closed?

**Comment by mdellweg** [comment]
I think, i would at least wait for a second data repair command. It might tell us the answer to whether more than `--dry-run` flags are likely and help design a common interface.

**Pull request closed without merging**
