### PR TITLE
Add /docs/swagger/ URL for swagger API view

### PR DESCRIPTION
**Pull request by alikins**
[noissue]

### CODE REVIEW

**Comment by dkliban** [comment]
What is the difference between this endpoint and the current /pulp/api/v3/docs/ endpoint?

**Comment by alikins** [comment]
@dkliban /pulp/api/v3/docs/ endpoint uses ReDoc for ui, /pulp/api/v3/docs/swagger/ uses swaggerui for ui

**Comment by dkliban** [comment]
@alikins I'd like to add these alternative docs. Could you add a sentence about them to this page in our docs? https://docs.pulpproject.org/rest_api.html

**Comment by dkliban** [comment]
@alikins I am going to close this PR for now. Feel free to re-open it when you can finish adding the docs.

**Pull request closed without merging**
