### PR TITLE
Remove coreapi dependency

### PR DESCRIPTION
**Pull request by mdellweg**
fixes #6583
https://pulp.plan.io/issues/6583

### CODE REVIEW

**Comment by evgeni** [comment]
Well, that was easy 😅

cc @ekohl

**Comment by mdellweg** [comment]
It was worth a try to just remove the dependency.

**Comment by ekohl** [comment]
Nice! What was it providing?

**Comment by mdellweg** [comment]
I think, it was the predecessor of openapi. And it wasn't even used anymore in pulp.

**Pull request merged**
