### PR TITLE
Teach artifact_stages:_needed_remote_artifacts() to not return dupes.

### PR DESCRIPTION
**Pull request by ggainey**
fixes #8489
[nocoverage]

### CODE REVIEW

**Comment by ggainey** [comment]
This PR is draft until I see pulp_container tests running clean in CI. I'll open a PR there that requires this one to force the run. Once it's clean, this will be available for review and acceptance.

**Review by dralley — COMMENTED** [review]
This seems reasonable, but it only deduplicates within a batch, is that OK?

**Comment by ggainey** [comment]
> This PR is draft until I see pulp_container tests running clean in CI. I'll open a PR there that requires this one to force the run. Once it's clean, this will be available for review and acceptance.

Looks like pulp_container is unbroken with this : https://github.com/pulp/pulp_container/pull/277 - assuming I did the "Requireed PR" dance correctly, can someone check pliz?

**Comment by dralley** [comment]
@ggainey Looks right to me

**Review by mdellweg — COMMENTED** [review]
Looks reasonable to me.

**Review by daviddavis — APPROVED** [review]

**Review by mdellweg — APPROVED** [review]

**Pull request merged**
