### PR TITLE
Add readiness option to the status endpoint

### LINKED ISSUE #2844: As a k8s user, I want an endpoint for the readiness probe
**Is your feature request related to a problem? Please describe.**
Readiness probe need to ensure everything is working properly: workers, db, ...

**Describe alternatives you've considered**
Maybe a query string to the status endpoint

### PR DESCRIPTION
**Pull request by fao89**
closes #2844

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

### CODE REVIEW

**Comment by ipanova** [comment]
/healthz endpoint can be a good candidate
https://stackoverflow.com/questions/43380939/where-does-the-convention-of-using-healthz-for-application-health-checks-come-f

**Comment by dralley** [comment]
Is this an urgent concern (enough to be a blocker)?  This seems potentially subtle enough to not want to rush last minute.  Also it seems like a good intern first task

**Comment by fao89** [comment]
> Is this an urgent concern (enough to be a 3.20 blocker)? This seems potentially subtle enough to not want to rush last minute. Also it seems like a good intern first task

Currently, the operator in production is using the status endpoint for the liveness probe. Which means the API pod will be up and running even if all the workers are down, for example. 
I don't know how critical it could be

**Comment by fao89** [comment]
I'm working with an alternative to this PR:
https://github.com/pulp/pulp-operator/pull/450

**Comment by fao89** [comment]
Operator PR worked, so it makes this less urgent
I'll close this PR

**Comment by fao89** [comment]
> Is this an urgent concern (enough to be a 3.20 blocker)? This seems potentially subtle enough to not want to rush last minute. Also it seems like a good intern first task

+1 for intern task

**Pull request closed without merging**
