### PR TITLE
Added csrf_token passing to django optional_logout

### PR DESCRIPTION
**Pull request by chtaylo2**
fixes: #5250

### CODE REVIEW

**Review by dkliban — DISMISSED** [review]

**Comment by dkliban** [comment]
@chtaylo2 the commit message needs to say 'fixes: #5250'.

**Comment by ggainey** [comment]
> @chtaylo2 the commit message needs to say 'fixes: #5250'.

And, so it gets picked up in the changelog an entry in CHANGES/ that describes what's fixed from an end-user's POV :) You can see (some) docs for what we look for/need in PRs here https://docs.pulpproject.org/pulpcore/contributing/git.html#changelog-update

(Note: we're in the middle of doing some major doc-rework; apologies for anything you find that's out of date...)

**Comment by dkliban** [comment]
please add a `CHANGES/5250.bugfix` file that describes what was fixed. 'Fixed the 500 error when requesting the status API using a browser.'

**Review by dkliban — APPROVED** [review]
Thank you very much for the contribution. Sorry about the PR friction.

**Comment by chtaylo2** [comment]
Thank you @dkliban. Happy to contribute and continue making the software better

**Review by ggainey — APPROVED** [review]
Great - thanks for the contribution!!

**Pull request merged**
