### PR TITLE
Remove the ansible collection from the recommendation

### LINKED ISSUE #3430: Remove "Recommended" from Ansible Installation
https://docs.pulpproject.org/pulpcore/installation/instructions.html#ansible-installation-recommended

### PR DESCRIPTION
**Pull request by fao89**
closes #3430

### CODE REVIEW

**Review by mdellweg — APPROVED** [review]

**Comment by gerrod3** [comment]
The ansible installer is still valid for 3.22, no? I think we should accept this PR after 3.22 has been release. Also, we should add documentation for the new recommend way of installing Pulp.

**Comment by fao89** [comment]
> The ansible installer is still valid for 3.22, no? I think we should accept this PR after 3.22 has been release. Also, we should add documentation for the new recommend way of installing Pulp.

why keeping point users to pulp_installer when it is about to be gone?
If they follow this now, they will install 3.22, and couple months after they will worry about migrating

**Comment by gerrod3** [comment]
> why keeping point users to pulp_installer when it is about to be gone? If they follow this now, they will install 3.22, and couple months after they will worry about migrating

I would like to see documentation for the install method replacing it. If that is coming in a separate PR, then I can accept this one now.

**Comment by ipanova** [comment]
We could keep the ansible installation in docs and in parenthesis mention it is going to be the last 3.22 release.
In a separate PR when adding the replacement ansible install can go away.

**Comment by fao89** [comment]
> We could keep the ansible installation in docs and in parenthesis mention it is going to be the last 3.22 release. In a separate PR when adding the replacement ansible install can go away.

Who would click in installation section in pulpcore docs?
A: **New** users

Why a new user wants to know about the installation that won't be supported anymore?

**Review by ipanova — APPROVED** [review]

**Pull request merged**
