### PR TITLE
Serialized global reclaim space, global repair artifacts tasks.

### LINKED ISSUE #3786: Global tasks like repair or reclaim should probably not run in parallel
**Version**
Please provide the versions of the pulpcore and plugin packages in use, and how they are installed.  If you are using Pulp via Katello, please provide the Katello version.

**Describe the bug**
Global tasks that involve all repos like repair or reclaim should run one at a time, like orphan cleanup https://github.com/pulp/pulpcore/blob/main/pulpcore/app/viewsets/orphans.py#L29

**To Reproduce**

**Expected behavior**

**Additional context**
Add any other context about the problem here.  Please provide links to any previous discussions via Discourse or Bugzilla.

### PR DESCRIPTION
**Pull request by ipanova**
closes #3786

### CODE REVIEW

**Review by gerrod3 — APPROVED** [review]

**Comment by mdellweg** [comment]
I thought, we wanted to prevent repair and reclaim to run in parallel. Would it make sense to take orphan cleanup into the mix, and ensure that only one of these dangerous tasks runs at a time?

**Comment by dralley** [comment]
You mean, by locking on some shared "global" resource (generic name) as opposed to individual global locks for repair, orphans, & reclaim?

**Comment by mdellweg** [comment]
> You mean, by locking on some shared "global" resource (generic name) as opposed to individual global locks for repair, orphans, & reclaim?

actually a global exclusive resource like `/pulp/api/dangerous/file/operation/`. Maybe that would be a bit much, but currently you can run repair and reclaim (which are kind of reciprocal to each other) concurrently.

**Comment by ipanova** [comment]
@mdellweg that goal of this PR was to not allow running 2 reclaim or 2 repairs in parallel.
Reclaim and repair are not exactly reciprocal, Reclaim deletes even the artifact row in DB , while repair task is focused on the reparation on broken artifacts that are present in db.

https://github.com/pulp/pulpcore/blob/main/pulpcore/app/tasks/reclaim_space.py#L62
https://github.com/pulp/pulpcore/blob/main/pulpcore/app/tasks/repository.py#L104

**Comment by ipanova** [comment]
But, I am not excluding possibility of a scenario that could cause issues for these tasks running in parallel. i.e these 2  tasks 
are  ran on the same repo A and content B that also happens to be 'broken' aka bitrot.

In any case, can we wait when we cross this brings with a real issue happening in our hands?

**Pull request merged**
