### PR TITLE
Remove custom pytest hook and move pytest markers from pulp-smash

### PR DESCRIPTION
**Pull request by hstct**
[noissue]

### CODE REVIEW

**Review by mdellweg — APPROVED** [review]
Although we could try to make this hook implementation optional, i think this is what we discussed, and we can always bring it back once we sorted out the pulp-smash story.

**Comment by hstct** [comment]
This hook will cause the CI pipeline to fail and don't run any functional tests if you don't install `pulp-smash` as a test requirement. From the matrix chat it seems that it is not really used anyway and the consensus was to just remove it.

It will run into this error [here](https://github.com/pulp/pulp_deb/actions/runs/5655044235/job/15319353732#step:10:1721)

With the removal the tests now run again: https://github.com/pulp/pulp_deb/pull/851

**Comment by dkliban** [comment]
is this not used anywhere?

**Comment by mdellweg** [comment]
> is this not used anywhere?

@dkliban not in any CI at least (It contradicts the parallel execution of tests).
If you are a regular user of this feature, we need to find a way to make the implementation of this hook dependent of the existence of its declaration (currently in pulp-smash).

**Comment by lubosmj** [comment]
Can we also move this from pulp_smash: https://github.com/pulp/pulp-smash/blob/2ded6671e0f32c51e70681467199e8a195f7f5fe/pulp_smash/pulp3/pytest_plugin/__init__.py#L76? I think @hstct mentioned that without that, he sees some warnings in the pulp_deb's CI.

**Comment by mdellweg** [comment]
> Can we also move this from pulp_smash: https://github.com/pulp/pulp-smash/blob/2ded6671e0f32c51e70681467199e8a195f7f5fe/pulp_smash/pulp3/pytest_plugin/__init__.py#L76? I think @hstct mentioned that without that, he sees some warnings in the pulp_deb's CI.

Only the second half of it, but yes, we should.

**Comment by hstct** [comment]
> > Can we also move this from pulp_smash: https://github.com/pulp/pulp-smash/blob/2ded6671e0f32c51e70681467199e8a195f7f5fe/pulp_smash/pulp3/pytest_plugin/__init__.py#L76? I think @hstct mentioned that without that, he sees some warnings in the pulp_deb's CI.
> 
> Only the second half of it, but yes, we should.

I can include this to this PR or open a new one whatever is preferred :slightly_smiling_face:

**Review by dkliban — APPROVED** [review]

**Pull request merged**
