### PR TITLE
Create a base class for Signing Services

### PR DESCRIPTION
**Pull request by mayaCostantini**
Related to https://github.com/pulp/pulpcore/issues/3952

Implements an abstract base class for Signing Services to enable creating new types without GPG-specific attributes.

### CODE REVIEW

**Comment by mayaCostantini** [comment]
cc @rochacbruno @newswangerd

**Comment by lubosmj** [comment]
We miss the migration here, don't we? You can create the migrations by running `pulpcore-manager makemigrations`.

Do not forget to add "closes #3952" to the commit message.

**Comment by mdellweg** [comment]
I think the fact that we don't see the migration is that this base class is marked as abstract.
We have had our fair share of trouble with the abstract BaseDistribution model for it to be inherited by plugins. Let's not repeat this.

**Comment by mayaCostantini** [comment]
Thanks @lubosmj I modified the commit message. Also I tried running `makemigrations` but no changes were detected. @mdellweg would you mind sharing more about the issue plugins are having with abstract classes?

**Comment by mdellweg** [comment]
Sorry, for the late answer. But an abstract base class in the plugin api will produce incompatibility issues whenever it changes in the slightest way, because that will require plugins to have a migration for that change in the new version and at the same time require not to have it for older versions of pulpcore.

**Comment by mayaCostantini** [comment]
I see, in this case is there any alternative you would recommend?

**Comment by mdellweg** [comment]
I believe we would make it a "proper" base class with a real db table. And that would involve writing a migration to extend the existing records to the new subclass.

**Comment by mayaCostantini** [comment]
Thanks @mdellweg, I tried removing the `class Meta` section to turn the class into a non-abstract one, but no changes are found when trying to run `pulpcore-manager makemigrations`. Do you have any idea why?

**Pull request closed without merging**
