### PR TITLE
Add test_tasking module

### PR DESCRIPTION
**Pull request by mdellweg**
This moved over from pulp_file.

[noissue]

### CODE REVIEW

**Comment by mdellweg** [comment]
Hah! One of the tests is flakey. It seems like a canceled task can have `finished_at=None`, but also set to something _meaningful_!?

**Comment by mdellweg** [comment]
Is "finished_at" supposed to be set on a canceled task?

**Comment by dkliban** [comment]
@mdellweg A task that is cancelled before it is finished should not have a `finished_at` set, but it should have a `cancelled_at` set. A user can't cancel a finished task. So the two fields are mutually exclusive. At least that is my understanding. However, it seems like this is not true in practice and perhaps we should file an issue about that.

**Comment by mdellweg** [comment]
> @mdellweg A task that is cancelled before it is finished should not have a `finished_at` set, but it should have a `cancelled_at` set. A user can't cancel a finished task. So the two fields are mutually exclusive. At least that is my understanding. However, it seems like this is not true in practice and perhaps we should file an issue about that.

That is exactly what the tests assert now, except that we do not have a `canceled_at` field. Can you write an issue if that is desired?

**Comment by dkliban** [comment]
@mdellweg I filed https://github.com/pulp/pulpcore/issues/3319

**Review by bmbouter — APPROVED** [review]
This is really nice!

**Pull request merged**
