### PR TITLE
Removed ``retained_versions`` feature from tech preview.

### PR DESCRIPTION
**Pull request by ipanova**
closes #8617

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

### CODE REVIEW

**Review by mdellweg — APPROVED** [review]

**Comment by daviddavis** [comment]
What’s the reasoning for removing this from tech preview in 3.14?

**Comment by ipanova** [comment]
> What’s the reasoning for removing this from tech preview in 3.14?

https://pulp.plan.io/projects/pulp/issues?fixed_version_id=218&set_filter=1&status_id=o

**Comment by daviddavis** [comment]
See my comment here: https://pulp.plan.io/issues/8617#note-1

Personally I would keep the tech preview until Galaxy has had a chance to review and sign off on it.

**Comment by ipanova** [comment]
> See my comment here: https://pulp.plan.io/issues/8617#note-1
> 
> Personally I would keep the tech preview until Galaxy has had a chance to review and sign off on it.

I have seen that comment but it was not clear to me that this implies it should *not* go into 3.14
I am happy to close the PR but I am going to remove the 3.14 milestone then.

**Review by mdellweg — APPROVED** [review]

**Comment by ipanova** [comment]
still waiting on automation hub to provide feedback before we take off the tech-preview.

**Comment by dralley** [comment]
Moving to draft since it's off the table for 3.15

**Comment by bmbouter** [comment]
@newswangerd did galaxy NG enable and test this feature? I'm asking because we tend to remove tech preview after the stakeholder driving a feature confirms it's working as expected.

**Comment by newswangerd** [comment]
@bmbouter we're testing it now

**Comment by bmbouter** [comment]
> @bmbouter we're testing it now. The changes that use this just got merged into galay_ng as part of the update to 3.15

Great thanks for the info. When you feel confident the feature is as you all desire, if possible, can you comment back on here for us to merge. We'll leave it at draft until then. Thanks!

**Comment by bmbouter** [comment]
I'd like us to get more data on usage of this feature before removing the tech preview. Also I think we should close these PRs that have been open for so long without a clear plan on when the tech preview labels will be removed.

**Pull request closed without merging**
