### PR TITLE
Caching OpenAPI schema

### PR DESCRIPTION
**Pull request by fao89**
https://pulp.plan.io/issues/8830
closes #8830

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

### CODE REVIEW

**Review by mdellweg — COMMENTED** [review]
:+1:
Loving it.
There is one thing to consider though: If you are in a dev environment, and you are changing some api, this would not be reflected by this caching. And you'd need to delete that file by hand over and over.
I see a few solutions to this:
* Add a setting to not cache it in dev environments.
* Detect if we are in a volatile environment and disable caching accordingly
  * is there a `dev` in any plugin version?
  * is any plugin installed with `pip -e`
* Remove that file with `pstart` and `prestart`

**Comment by daviddavis** [comment]
> Add a setting to not cache it in dev environments.

We don't use Django's [DEBUG setting](https://docs.djangoproject.com/en/3.2/ref/settings/#debug) but maybe we should?

**Comment by bmbouter** [comment]
At the pulpcore meeting we discussed wanting to investigate the memory leak as an alternative fix to this approach.

**Comment by mdellweg** [comment]
I have another approach for this: We could add a post installation step that generates the file and puts it on disk.
Whenever the file is there, we serve it, if not, we do the generate on the fly.

**Comment by bmbouter** [comment]
I think we should close this for a few reasons. 1) I don't think we don't really want caching. It can lead to problems I believe. 2) If we did want caching we wouldn't add the feature to Pulp; I think we'd add it to the dependency providing this endpoint to start with. 3) The folks affected by the memory leak already put in their workaround.

**Comment by fao89** [comment]
we had 2 views for the OpenAPI and the one that most concerned me got removed at https://github.com/pulp/pulpcore/pull/1593
So I agree we can close this PR

**Pull request closed without merging**
