### PR TITLE
Add --preload to pulpcore-{api/content}

### LINKED ISSUE #4368: missing command line options in new app entrypoint
**Version**
3.33.0

**Describe the bug**
in 4def68e1f1bd4ffcae5352ee9d6ff7404759a19e a new app entrypoint was added to be used instead of calling gunicorn directly, however it is missing (at least) the `--preload` switch that gunicorn supports and Katello uses

https://github.com/benoitc/gunicorn/blob/master/gunicorn/config.py#L992

https://github.com/theforeman/puppet-pulpcore/commit/b8189466629b05df91fe90fbb7f741e2e9c27786

**To Reproduce**
try to call `pulpcore-content` with `--preload`

**Expected behavior**
app boots

**Additional context**
Add any other context about the problem here.  Please provide links to any previous discussions via Discourse or Bugzilla.

### PR DESCRIPTION
**Pull request by mdellweg**
fixes #4368

### CODE REVIEW

**Comment by mdellweg** [comment]
@evgeni Would you mind testing that this actually works as designed?

**Review by ipanova — APPROVED** [review]

**Review by decko — APPROVED** [review]

**Comment by decko** [comment]
@mdellweg just waiting for @evgeni response to merge it.

**Comment by mdellweg** [comment]
When preloading, it fails it's own consistency check. XD
`Error: This app must be executed using pulpcore-api entrypoint.`

**Comment by evgeni** [comment]
the code looks fine, but I didn't have the time to actually spin up a setup and test this, I trust y'all :)

**Pull request merged**
