### PR TITLE
Fix syncs of repos from file:// urls

### PR DESCRIPTION
**Pull request by dralley**
closes: #9003
https://pulp.plan.io/issues/9003

### CODE REVIEW

**Comment by dralley** [comment]
See: https://pulp.plan.io/issues/9003#note-5

**Comment by bmbouter** [comment]
If you can look into writing a test for this that would be really great.

**Comment by ianballou** [comment]
I patched this into my Katello with pulpcore 3.14 and I'm seeing this error in my tests:
```
Katello::Errors::Pulp3Error: [Errno 2] No such file or directory: '/var/lib/pulp/sync_imports/test_repos/zoo/repodata/repomd.xml.asc'
```

There is a `repomd.xml` but no `repomd.xml.asc` on my filesystem.

**Comment by dralley** [comment]
Thanks @ianballou.  That would be an RPM plugin bug - we expect that these files might not always exist but we check for them because there's no manifest that enumerates them otherwise.  The case where the files fail with 404 is handled but not FileNotFound.

https://github.com/pulp/pulp_rpm/blob/master/pulp_rpm/app/tasks/synchronizing.py#L639-L647

That's an easy fix and I can address it in a few minutes.

**Comment by ianballou** [comment]
@dralley I made an issue for the bug I hit above: https://pulp.plan.io/issues/9021

**Review by daviddavis — APPROVED** [review]

**Review by bmbouter — APPROVED** [review]
We gotta figure the testing out, but I'm hearing we gotta merge this asap. The fix part looks good so lgtm.

**Pull request merged**
