### PR TITLE
Bump django to 3.2

### PR DESCRIPTION
**Pull request by daviddavis**
fixes #9018

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

### CODE REVIEW

**Comment by dralley** [comment]
Also update all of the `contrib.JSONField` to the official Django JSONField.  It just migrates in place, no need to do anything special.

**Comment by daviddavis** [comment]
Yes, thank you for the reminder. I think we'll want to address that in a follow up commit since it's not required for switching to django 3.2 and I heard we might want to cherry pick this django 3.2 change (and thus will want to keep the footprint small). I can file a task if you agree.

**Comment by dralley** [comment]
:+1:

**Comment by daviddavis** [comment]
Here we go: https://pulp.plan.io/issues/8488

**Review by mdellweg — APPROVED** [review]

**Review by bmbouter — APPROVED** [review]
This looks good to me. Thank you @daviddavis !

**Pull request merged**
