### PR TITLE
Artifacts are unique per domain.

### PR DESCRIPTION
**Pull request by ipanova**
[noissue]

### CODE REVIEW

**Review by lubosmj — APPROVED** [review]
💚

**Comment by mdellweg** [comment]
Can you improve the commit message a bit?
e.g. start with "Refactor artifact queries" and the fact that they are unique makes for a perfect explanation in the lines after the first.

**Comment by decko** [comment]
@ipanova do you think an index on the `domain` foreign key could improve this query?

**Review by dkliban — APPROVED** [review]

**Review by mdellweg — CHANGES_REQUESTED** [review]
Please adjust the commit message to some thing more meaningful.

**Comment by ipanova** [comment]
> @ipanova do you think an index on the `domain` foreign key could improve this query?

Yes, I think so. We use a composite index here where pulp-domain is on the second place in the list https://www.cybertec-postgresql.com/en/combined-indexes-vs-separate-indexes-in-postgresql/

**Comment by ipanova** [comment]
@mdellweg  done

@decko you want this backported somewhere?

**Comment by ipanova** [comment]
> > @ipanova do you think an index on the `domain` foreign key could improve this query?
> 
> Yes, I think so. If using a composite index it will not work well in all cases  https://www.cybertec-postgresql.com/en/combined-indexes-vs-separate-indexes-in-postgresql/

The pulp_domain is already listed there as index. Postgres automatically creates indexes for PK and unique constraints part of which `pulp_domain` is  https://github.com/pulp/pulpcore/blob/main/pulpcore/app/models/content.py#L247

```
pulp=# SELECT * FROM pg_indexes WHERE tablename='core_artifact';                                                                                                                                                                              
-[ RECORD 1 ]----------------------------------------------------------------------------------------------------------------------------------                                                                                               
schemaname | public                                                                                                                                                                                                                           
tablename  | core_artifact                                                                                                                                                                                                                    
indexname  | core_artifact_pkey                                                                                                                                                                                                               
tablespace |                                                                                                                                                                                                                                  
indexdef   | CREATE UNIQUE INDEX core_artifact_pkey ON public.core_artifact USING btree (pulp_id)                                                                                                                                             
-[ RECORD 2 ]----------------------------------------------------------------------------------------------------------------------------------                                                                                               
schemaname | public                                                                                                                                                                                                                           
tablename  | core_artifact                                                                                                                                                                                                                    
indexname  | core_artifact_sha256_ee7b97eb                                                                                                                                                                                                    
tablespace |                                                                                                                                                                                                                                  
indexdef   | CREATE INDEX core_artifact_sha256_ee7b97eb ON public.core_artifact USING btree (sha256)                                                                                                                                          
-[ RECORD 3 ]----------------------------------------------------------------------------------------------------------------------------------                                                                                               
schemaname | public                                                                                                                                                                                                                           
tablename  | core_artifact                                                                                                                                                                                                                    
indexname  | core_artifact_sha384_f484b46a                                                                                                                                                                                                    
tablespace |                                                                                                                                                                                                                                  
indexdef   | CREATE INDEX core_artifact_sha384_f484b46a ON public.core_artifact USING btree (sha384)                                                                                                                                          
-[ RECORD 4 ]----------------------------------------------------------------------------------------------------------------------------------                                                                                               
schemaname | public                                                                                                                                                                                                                           
tablename  | core_artifact                                                                                                                                                                                                                    
indexname  | core_artifact_sha512_39254488                                                                                                                                                                                                    
tablespace |                                                                                                                                                                                                                                  
indexdef   | CREATE INDEX core_artifact_sha512_39254488 ON public.core_artifact USING btree (sha512)                                                                                                                                          
-[ RECORD 5 ]----------------------------------------------------------------------------------------------------------------------------------                                                                                               
schemaname | public                                                                                                                                                                                                                           
tablename  | core_artifact                                                                                                                                                                                                                    
indexname  | core_artifact_sha384_pulp_domain_id_46f3e0f5_uniq                                                                                                                                                                                
tablespace |                                                                                                                                                                                                                                  
indexdef   | CREATE UNIQUE INDEX core_artifact_sha384_pulp_domain_id_46f3e0f5_uniq ON public.core_artifact USING btree (sha384, pulp_domain_id)                                                                                               
-[ RECORD 6 ]----------------------------------------------------------------------------------------------------------------------------------                                                                                               
schemaname | public                                                                                                                                                                                                                           
tablename  | core_artifact                                                                                                                                                                                                                    
indexname  | core_artifact_sha512_pulp_domain_id_5e5f2eb0_uniq                                                                                                                                                                                
tablespace |                                                                                                                                                                                                                                  
indexdef   | CREATE UNIQUE INDEX core_artifact_sha512_pulp_domain_id_5e5f2eb0_uniq ON public.core_artifact USING btree (sha512, pulp_domain_id)    
-[ RECORD 7 ]----------------------------------------------------------------------------------------------------------------------------------                                                                                      [67/1961]
schemaname | public                                                                                                                                                                                                                           
tablename  | core_artifact                                                                                                                                                                                                                    
indexname  | core_artifact_md5_8de3b667                                                                                                                                                                                                       
tablespace | 
indexdef   | CREATE INDEX core_artifact_md5_8de3b667 ON public.core_artifact USING btree (md5)
-[ RECORD 8 ]----------------------------------------------------------------------------------------------------------------------------------
schemaname | public
tablename  | core_artifact
indexname  | core_artifact_md5_8de3b667_like
tablespace | 
indexdef   | CREATE INDEX core_artifact_md5_8de3b667_like ON public.core_artifact USING btree (md5 varchar_pattern_ops) 
-[ RECORD 9 ]----------------------------------------------------------------------------------------------------------------------------------
schemaname | public
tablename  | core_artifact
indexname  | core_artifact_sha1_65ed6874
tablespace | 
indexdef   | CREATE INDEX core_artifact_sha1_65ed6874 ON public.core_artifact USING btree (sha1)
-[ RECORD 10 ]---------------------------------------------------------------------------------------------------------------------------------
schemaname | public
tablename  | core_artifact
indexname  | core_artifact_sha1_65ed6874_like
tablespace | 
indexdef   | CREATE INDEX core_artifact_sha1_65ed6874_like ON public.core_artifact USING btree (sha1 varchar_pattern_ops)
-[ RECORD 11 ]---------------------------------------------------------------------------------------------------------------------------------
schemaname | public
tablename  | core_artifact
indexname  | core_artifact_sha224_f1a1edf3
tablespace | 
indexdef   | CREATE INDEX core_artifact_sha224_f1a1edf3 ON public.core_artifact USING btree (sha224)
-[ RECORD 12 ]---------------------------------------------------------------------------------------------------------------------------------
schemaname | public
tablename  | core_artifact
indexname  | core_artifact_sha224_f1a1edf3_like
tablespace | 
indexdef   | CREATE INDEX core_artifact_sha224_f1a1edf3_like ON public.core_artifact USING btree (sha224 varchar_pattern_ops)
-[ RECORD 13 ]---------------------------------------------------------------------------------------------------------------------------------
schemaname | public
tablename  | core_artifact
indexname  | core_artifact_sha256_ee7b97eb_like
tablespace | 
indexdef   | CREATE INDEX core_artifact_sha256_ee7b97eb_like ON public.core_artifact USING btree (sha256 varchar_pattern_ops)
-[ RECORD 14 ]---------------------------------------------------------------------------------------------------------------------------------
schemaname | public
tablename  | core_artifact
indexname  | core_artifact_sha384_f484b46a_like
tablespace | 
indexdef   | CREATE INDEX core_artifact_sha384_f484b46a_like ON public.core_artifact USING btree (sha384 varchar_pattern_ops)
-[ RECORD 15 ]---------------------------------------------------------------------------------------------------------------------------------
schemaname | public
tablename  | core_artifact
indexname  | core_artifact_sha512_39254488_like
tablespace | 
indexdef   | CREATE INDEX core_artifact_sha512_39254488_like ON public.core_artifact USING btree (sha512 varchar_pattern_ops)
-[ RECORD 16 ]---------------------------------------------------------------------------------------------------------------------------------
schemaname | public
tablename  | core_artifact
indexname  | core_artifact_sha256_pulp_domain_id_8efff3e8_uniq
tablespace | 
indexdef   | CREATE UNIQUE INDEX core_artifact_sha256_pulp_domain_id_8efff3e8_uniq ON public.core_artifact USING btree (sha256, pulp_domain_id)
-[ RECORD 17 ]---------------------------------------------------------------------------------------------------------------------------------
schemaname | public
tablename  | core_artifact
indexname  | core_artifact_pulp_domain_id_ff16c936
tablespace | 
indexdef   | CREATE INDEX core_artifact_pulp_domain_id_ff16c936 ON public.core_artifact USING btree (pulp_domain_id)

```

**Comment by decko** [comment]
> @decko you want this backported somewhere?

@ipanova I was thinking about just the supported branches. `3.49` is the only one I have in mind right now.

**Review by mdellweg — APPROVED** [review]

**Review by decko — APPROVED** [review]

**Pull request merged**
