### PR TITLE
Fixed partial and general update calls.

### PR DESCRIPTION
**Pull request by ipanova**
closes #6565
https://pulp.plan.io/issues/6565

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

### CODE REVIEW

**Comment by ipanova** [comment]
```
In [3]: x=None                                                                                                                                                                                                     

In [4]: hashlib.sha256(bytes(x, "utf-8")).hexdigest()                                                                                                                                                              
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-38b88e0b2294> in <module>
----> 1 hashlib.sha256(bytes(x, "utf-8")).hexdigest()

TypeError: encoding without a string argument
```

**Comment by jlsherrill** [comment]
this appears to have fixed the issue for me!

**Comment by dralley** [comment]
The CI passed but it hasn't notified github :(

**Comment by jlsherrill** [comment]
would it be possible to get this in a 3.3.1 ?

**Pull request merged**
