### PR TITLE
Use bulk touch() when processing Artifacts and Content

### PR DESCRIPTION
**Pull request by dkliban**
This patch only addresses part of the problem described in issue #9243. Another patch
is needed to address the inefficiency of the repository version modify operation.

re: #9243

### CODE REVIEW

**Review by dralley — APPROVED** [review]

**Comment by dralley** [comment]
@dkliban I created a backport issue, we will just want to be careful that if there are multiple PRs / commits, they all get backported.

**Review by daviddavis — APPROVED** [review]

**Comment by dralley** [comment]
Since we have 3 open PRs that will conflict I'm thinking the best order to merge the PRs is:

1. This one
2. Gerrod's fix for 9101
3. The async connections PR

Because #3 isn't going to be backported.  Agreed @dkliban ?

**Comment by dkliban** [comment]
> Since we have 3 open PRs that will conflict I'm thinking the best order to merge the PRs is:
> 
>     1. This one
> 
>     2. Gerrod's fix for 9101
> 
>     3. The async connections PR
> 
> 
> Because #3 isn't going to be backported. Agreed @dkliban ?

This is true for upstream. However, I could see someone wanting to add Django 3.2 support for pulpcore 3.14 downstream.

**Comment by dralley** [comment]
I kind of hope we don't do that, but even if we do, it still makes sense (because the backport would happen much later, after the others are backported)

Is this ready to go?

**Pull request merged**
