### PR TITLE
Moves TaskGroup.finish() to outside the loop in the replication task

### PR DESCRIPTION
**Pull request by dkliban**
fixes: #4175

### CODE REVIEW

**Review by gerrod3 — APPROVED** [review]
This wouldn't affect our tests since we only have one plugin (file) so `supported_replicators` would have a length of one, correct?

**Comment by dkliban** [comment]
> This wouldn't affect our tests since we only have one plugin (file) so `supported_replicators` would have a length of one, correct?

I don't think it affects the tests for the reason you mention.

**Comment by mdellweg** [comment]
We identified that "all_tasks_dispatched" is really not so much helpful, because it usually does not get set in case of an error. So we adjusted our task group waiting algorithms to not care about it.
Maybe we'll remove it someday.

**Review by mdellweg — COMMENTED** [review]
Should `task_group.finish()` be inside a finally statement?
Does any of the subtasks fork even more tasks?

**Comment by dkliban** [comment]
What is set_failed() checked if the task is the earliest created task of a task group and then set the completed flag on the task group?


https://github.com/pulp/pulpcore/blob/main/pulpcore/app/models/task.py#L274

**Review by mdellweg — APPROVED** [review]
It is really not sure where the task_group.finish feature is heading. You don't even need it to identify the state of a task group.
This however is more correct than before.

**Pull request merged**
