### PR TITLE
Problem: pulp_rpm 3.3.0 cannot install (& F32 upgrade)

### PR DESCRIPTION
**Pull request by mikedep333**
on the pulp-operator pulp container because Fedora's createrepo_c
 is too old
    
 Solution: Temporarily replace the createrepo_c RPM with its
 build-dependencies, and let createrepo_c get installed &
 built from PyPI.

fixes: #6523

Developed on top of this change:

containers: Upgrade to Fedora 32
    
fixes: #6522

### CODE REVIEW

**Comment by dralley** [comment]
@mikedep333 Needs a changelog entry

**Comment by mikedep333** [comment]
This seems to be failing because of a bug in the Travis scripts: It is trying to use the Travis Python version (3.7) in the containers. But going from Fedora 30 containers to Fedora 32 means going from Python 3.7 to 3.8.

**Comment by fao89** [comment]
@mikedep333 do you think we can reopen it?

**Comment by mikedep333** [comment]
@fao89 yes, we just have to fix the bug https://github.com/pulp/pulpcore/pull/657#issuecomment-616575810

**Comment by fao89** [comment]
> @fao89 yes, we just have to fix the bug [#657 (comment)](https://github.com/pulp/pulpcore/pull/657#issuecomment-616575810)

the problem was with unit tests here:
https://github.com/pulp/plugin_template/blob/master/templates/travis/.travis/script.sh.j2#L91
As plugins don't use operator anymore, I think the bug is already addressed

**Comment by fao89** [comment]
@mikedep333 maybe it is better to move this container thing out of pulpcore, to a repo we (CI/CD team) have more control

**Comment by mikedep333** [comment]
@fao89 The plan has been to move it out. We agreed on pulp-operator, but we need to figure out the CI details and folder structure and all. There's probably a redmine ticket.

**Comment by goosemania** [comment]
@fao89 , @mikedep333 , do we still need it? or should we close it?

**Comment by fao89** [comment]
> @fao89 , @mikedep333 , do we still need it? or should we close it?

it was moved to pulp-operator, we can close it

**Comment by goosemania** [comment]
Closing as per https://github.com/pulp/pulpcore/pull/657#issuecomment-684884770

**Pull request closed without merging**
