### PR TITLE
Change the order of authentication classes

### LINKED ISSUE #3730: The order of authentication classes causes Pulp to return 403 instead of 401 on failed authentication
https://github.com/pulp/pulpcore/blob/50bdd1ba0d2ce7ae4d6eef15a2dd7c569d49c03a/pulpcore/app/settings.py#L150

In pulp_container, we have a view that should handle insufficient, invalid, or valid credentials provided by users. If the users pass invalid credentials to that view, Pulp returns 403 instead of 401.

Changing the order of authentication classes could resolve the problem according to https://www.django-rest-framework.org/api-guide/authentication/#unauthorized-and-forbidden-responses.

> The first authentication class set on the view is used when determining the type of response.

### PR DESCRIPTION
**Pull request by lubosmj**
closes #3730

### CODE REVIEW

**Review by dralley — APPROVED** [review]

**Comment by lubosmj** [comment]
The change is visible from this test:

https://github.com/pulp/pulp_container/blob/6b5c6b4caaf54e95f3257ecd2387351d1f0cd667/pulp_container/tests/functional/api/test_token_authentication.py#L142

https://github.com/pulp/pulp_container/actions/runs/4669255842/jobs/8267470311#step:10:1961

**Comment by lubosmj** [comment]
re: https://github.com/pulp/pulp_container/pull/1257

**Review by mdellweg — APPROVED** [review]

**Comment by dralley** [comment]
I don't think so.  This seems more standard compliant

**Comment by ipanova** [comment]
Was this backported to older branches?

**Pull request merged**
