### PR TITLE
Fixed import deadlock by force-locking Tables Of Interest.

### PR DESCRIPTION
**Pull request by ggainey**
fixes #7904
[nocoverage]

### CODE REVIEW

**Comment by bmbouter** [comment]
Which tables does this lock? Is it the Content table?

**Comment by ggainey** [comment]
> Which tables does this lock? Is it the Content table?

The (newly-pushed) version locks each table it's about to import data into. The previous version suffered from a fatal cut-and-paste error...

While the current state of the PR fixes the deadlock, I'm not happy with it. Let's mark this as "draft", maybe with thought and discussion we can come up with a more elegant/performant solution.

**Comment by ipanova** [comment]
@ggainey  this is marked for 3.12 will this still be the case if you move it to draft state?

**Comment by ggainey** [comment]
> @ggainey this is marked for 3.12 will this still be the case if you move it to draft state?

I don't like this approach, but it may be our best bet. I will have time to do some different experiments in the next couple days. How about I say, "no later than Weds 31-MAR we'll call it for 3.12, or Not"?

**Comment by bmbouter** [comment]
Where in the code are we creating transactions that these inserts compete with?

**Comment by ggainey** [comment]
> Where in the code are we creating transactions that these inserts compete with?

This code competes with itself. Repositories are imported in parallel, import_repository_version() gets enqueued for each repo in the import-file. See https://github.com/pulp/pulpcore/blob/02e157f2e3edf21118be861aafa95530c1f004ac/pulpcore/app/tasks/importer.py#L419

**Review by daviddavis — APPROVED** [review]
I can't think of a better solution so LGTM.

**Comment by ggainey** [comment]
Closing - this is not the right way to approach this problem.

**Pull request closed without merging**
