### PR TITLE
Report the size of served artifacts

### LINKED ISSUE #4602: Add additional metrics reporting size of artifacts served
## Need / Background

When running on Pulp on cloud services the egress network costs serving data to off-cloud hosts can be very expensive. This is true regardless of if Pulp is serving the data directly (local filesystem storage) or if it's using an object storage backend.

Understanding these costs is key. It would be excellent to know answers to these questions:
* How much data did I serve for this Artifact request
* Which Repository (or at least Distribution) is this Artifact member of?
* Which Domain (if any) is this Artifact a member of?
* Where did this Artifact go (in a network sense, e.g. IP)?

## Proposal

Have the pulpcore-content app serve up this raw data as part of the per-request open telemetry data that is already reported as part of [basic enabling of otel support in pulpcore-content](https://github.com/pulp/pulpcore/issues/3829). Specifically have it report:

* Bytes of the Artifact served
* Domain the request is being handled as

The Distribution URL would be contained in the URL of the request which is already reported, so no additional work is needed there. Also the IP of the client is also contained in the data already so additional work isn't needed for that.

## One Detail about Object Storage

Note, in the case where Pulp is using Object storage, the Bytes reported needs to be the Artifact size (which Pulp knows in its DB). With Object storage the actual response from Pulp is a redirect which is very small. We need the Bytes of the Artifact, not the Bytes of the redirect request served.

### PR DESCRIPTION
**Pull request by lubosmj**
closes #4602

### CODE REVIEW

**Comment by lubosmj** [comment]
Continuation of https://github.com/pulp/pulpcore/pull/5169. This PR was opened for transparency purposes and it is not meant to be reviewed yet.

Here, I report metrics directly from the instrumentation middleware. However, it seems like the correctness of this approach is questionable because the collector might receive data from multiple instances of the counter and the size of served artifacts is not growing:

image

Seeing both of the implementations, I am suggesting to lean towards the following approach:
- store the value of served artifacts in some persistent storage with locking capabilities so no race conditions would appear by default
- this value will be increased every time we serve the content from Pulp
- once in a while, we will emit this value to the OTEL collector (like we do now for the accumulated size of domains) by leveraging the asynchronous counter instrument

**Comment by lubosmj** [comment]
Thinking about it more, does it make sense to report such metrics (i.e., the size of served data) if users have knowledge of egress traffics? I would like to believe that 3rd party content storages have capabilities to record such data in general.

**Comment by bmbouter** [comment]
The tools for reporting cost for things like S3 for example don't report on a per-bucket level. Our needs are to have it per domain (which is really per bucket). Also even if it did report in S3 per-bucket, there are other complexities such as a) delays in reporting and b) permissions are needed for users to access those cost reports which get pretty complex on AWS.

I think based on our needs having this data report into OTEL to let PROMQL query it would be ideal.

**Comment by decko** [comment]
To clarify what's expected outcomes of this task:

```
    How much data did I serve for this Artifact request
    Which Repository (or at least Distribution) is this Artifact member of?
    Which Domain (if any) is this Artifact a member of?
```
which on my understanding is "we don't want to see individual data about each artifact served, but the aggregation of all artifacts served. If we use the repository/distribution and the domain as labels/attributes, we can get the information that we need.

Also @lubosmj, I believe that you're right about using a `Counter`. This metric is monotonic, as it will only increase over time.

**Comment by bmbouter** [comment]
@decko I agree with your recap of what we need.

@lubosmj I totally missed the implementation question, but that's probably for the best as I really don't understand the specifics of OTEL data reporting types and aggregation.

If I've missed answering a question, please let me know because this work is important and I want to share info to unblock it.

**Comment by mdellweg** [comment]
Do we take ranged requests in to account?

**Comment by lubosmj** [comment]
> Do we take ranged requests in to account?

Can you elaborate on it? I guess an artifact is served from content-app as it is. At least, we know its size before returning any response. I record the size of an artifact after we retrieve information about it from the database.

**Comment by mdellweg** [comment]
We serve only part of the artifact, when the client requests a range (e.g. for chunked or continued downloads).

**Comment by lubosmj** [comment]
> We serve only part of the artifact, when the client requests a range (e.g. for chunked or continued downloads).

I understand. Though, if I get the size of an artifact from `artifact_file.size` in [_serve_content_artifact](https://github.com/pulp/pulpcore/blob/7297b25d5d62702c7f0762109ddd775daaf942a4/pulpcore/content/handler.py#L960) or `size` in [_stream_remote_artifact](https://github.com/pulp/pulpcore/blob/7297b25d5d62702c7f0762109ddd775daaf942a4/pulpcore/content/handler.py#L1027), we do not need to worry about the ranges, do we?

**Comment by mdellweg** [comment]
"How much data did I serve for this Artifact request" That sounds very much like the requested range to me.

**Comment by lubosmj** [comment]
> Each data point that is reported has a 'http_host' label on it. So even if the collector receives data about the same artifact from two different processes, it will store them as two separate data points.

@dkliban, I see. The problem we are trying to resolve now is that there might exist multiple instances of meters (possibly per each worker/process or even request in the worst case). These meters seem to fight against each other which results in reporting ambiguous data (?). As demonstrated in the screenshot, the visualization shows a non-growing curve for the number of artifacts served when a user downloads content in parallel.

**Comment by lubosmj** [comment]
> "How much data did I serve for this Artifact request" That sounds very much like the requested range to me.

@mdellweg, ah, so we should also **consider the requested range if provided**. Otherwise, we should be fine. Thanks for the input.

Also, another question is how can we ensure reporting a valid size of served artifacts if we issue redirects to the object storage? We do not know if the client would follow the redirect but we still need to report the size of a "potentially" served artifact.

**Comment by mdellweg** [comment]
> Also, another question is how can we ensure reporting a valid size of served artifacts if we issue redirects to the object storage? We do not know if the client would follow the redirect but we still need to report the size of a "potentially" served artifact.

And the redirect link could be used multiple times until it expires.

**Comment by bmbouter** [comment]
The possibility that the client could not follow the redirect or follow it several times is true.

I think it's ok to assume they will though. Under normal operation the redirect is followed once because typically the client is a cli like yum/dnf which will follow the redirect and follow it once.

**Comment by decko** [comment]
> The possibility that the client could not follow the redirect or follow it several times is true.
> 
> I think it's ok to assume they will though. Under normal operation the redirect is followed once because typically the client is a cli like yum/dnf which will follow the redirect and follow it once.

Also, it's a thing that's not under our control. I think we could consider an "error margin" for it given the possibilities described above.

**Comment by lubosmj** [comment]
As per our recent conversation with @dkliban, I am going to report the size of served artifacts by leveraging the [synchronous gauge](https://opentelemetry.io/docs/specs/otel/metrics/api/#gauge) instead of counter. These metrics will be afterwards grouped and summed by the prometheus server for further visualization. We will just report raw data and leave the evaluation on the prometheus server instead of doing all the computing on the Pulp's side.

**Comment by lubosmj** [comment]
Unfortunately, gauges are not working in this scenario because of the nature of the instrument, making the emitted metrics effectively indistinguishable.

Together with @decko, we decided to fall back to the counter. What I had observed in the past were two counters emitting different value with the same attributes, as pointed out by @decko -- one counter per one content-app instance (gunicorn runner) fought against each other. Now, we plan to add the name of content-app to the counter attributes to distinguish the emitted metrics properly to allow further aggregations. Users can then sum the values of these counters to get the total value per domain, like so: `sum by(domain) (pulp_artifacts_size_counter_bytes_total)`. Preliminary testing has shown that this approach works.

image

**Comment by lubosmj** [comment]
Closing in favour of: https://github.com/pulp/pulpcore/pull/5338. It appeared it is not that easy to fetch the name of a domain from within the instrumentation middleware.

So, I decided to implement a custom metrics class (like in the past) that holds the reference to the meter inside the pulpcore-content handler and is able to record all required information about domains and artifacts when initializing responses.

**Pull request closed without merging**
