### PR TITLE
Replace DictField with JSONField

### PR DESCRIPTION
**Pull request by lubosmj**
closes #8954

### CODE REVIEW

**Comment by daviddavis** [comment]
Hey this looks great, nice find :+1: 

How hard would it be to write a test?

**Comment by lubosmj** [comment]
> How hard would it be to write a test?

I do not know. I am not sure whether it is possible to send form data through the bindings. I am going to take a look at that. Stay tuned.

**Review by daviddavis — APPROVED** [review]
I looked at the bindings and didn't see any easy way to do it. So I'm approving this as is.

**Comment by lubosmj** [comment]
@daviddavis, just note that when you want to submit form data, you need to apply quotes around the `pulp_labels` value, like this:
```
(pulp) [vagrant@pulp3-source-fedora33 ~]$ http -v --form POST :/pulp/api/v3/remotes/file/file/ name=$RANDOM pulp_labels='{"environment":"dev"}' url='http://test'
POST /pulp/api/v3/remotes/file/file/ HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
Connection: keep-alive
Content-Length: 80
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: localhost
User-Agent: HTTPie/2.4.0

name=13764&pulp_labels=%7B%22environment%22%3A%22dev%22%7D&url=http%3A%2F%2Ftest

HTTP/1.1 201 Created
Access-Control-Expose-Headers: Correlation-ID
Allow: GET, POST, HEAD, OPTIONS
Connection: keep-alive
Content-Length: 522
Content-Type: application/json
Correlation-ID: 4dfe44d5412d49d5be03ba266f7e7088
Date: Fri, 09 Jul 2021 14:00:26 GMT
Location: /pulp/api/v3/remotes/file/file/68d9b8ee-a958-41aa-b058-f1443d43af0f/
Server: nginx/1.20.1
Vary: Accept, Cookie
X-Frame-Options: SAMEORIGIN

{
    "ca_cert": null,
    "client_cert": null,
    "connect_timeout": null,
    "download_concurrency": null,
    "headers": null,
    "max_retries": null,
    "name": "13764",
    "policy": "immediate",
    "proxy_url": null,
    "pulp_created": "2021-07-09T14:00:26.568756Z",
    "pulp_href": "/pulp/api/v3/remotes/file/file/68d9b8ee-a958-41aa-b058-f1443d43af0f/",
    "pulp_labels": {
        "environment": "dev"
    },
    "pulp_last_updated": "2021-07-09T14:00:26.568768Z",
    "rate_limit": null,
    "sock_connect_timeout": null,
    "sock_read_timeout": null,
    "tls_validation": false,
    "total_timeout": null,
    "url": "http://test"
}
```

Do you think we should add a note about that in the docs (`pulp_labels='{"environment":"dev"}'` vs `pulp_labels={"environment":"dev"}`)? It is all about the interpretation of the provided value (`name=13764&pulp_labels=%7B%22environment%22%3A%22dev%22%7D&url=http%3A%2F%2Ftest` vs `name=3761&pulp_labels=%7Benvironment%3Adev%7D&url=http%3A%2F%2Ftest`).

**Comment by dralley** [comment]
Should we file a backport for this for 3.14.z?

**Comment by daviddavis** [comment]
@lubosmj Yea, that sounds sufficient to me too. 

@dralley I think most people are not using form data (but maybe I'm wrong since I mostly use the api/cli) but I am not opposed to it.

**Comment by dralley** [comment]
I've been of the mind recently that we should default to backporting everything we can that doesn't cause conflicts, because we kept running into issues where we thought Katello didn't need something and then they ended up needing it.

It also goes a long way towards de-risking the prospect of Y-version upgrades.

Although I'm hoping we can automate it a bit more and find a way to avoid filing backport issues.

**Comment by dralley** [comment]
I think we should try to do a test, even if it doesn't use the bindings.  We can update it later if the bindings to grow that capability.

**Review by dralley — APPROVED** [review]

**Review by daviddavis — APPROVED** [review]

**Pull request merged**
