### PR TITLE
[Backport-3.49] Fix import in wsgi preventing startup

### LINKED ISSUE #5189: Fix import in wsgi preventing startup
**Version**
Confirmed with Katello folks using 3.49 branch.

**Describe the bug**
We're getting an error during the startup stage:
```python
Starting Pulp API Server...
Traceback (most recent call last):
  File "/usr/bin/pulpcore-api", line 33, in <module>
    sys.exit(load_entry_point('pulpcore==3.49.1', 'console_scripts', 'pulpcore-api')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pulpcore/app/entrypoint.py", line 140, in main
    PulpcoreApiApplication(options).run()
  File "/usr/lib/python3.11/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/usr/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
    ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/usr/lib/python3.11/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/usr/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pulpcore/app/entrypoint.py", line 95, in load
    import pulpcore.app.wsgi
  File "/usr/lib/python3.11/site-packages/pulpcore/app/wsgi.py", line 14, in <module>
    from pulpcore.app.util import init_domain_metrics_exporter
  File "/usr/lib/python3.11/site-packages/pulpcore/app/util.py", line 24, in <module>
    from pulpcore.app import models
  File "/usr/lib/python3.11/site-packages/pulpcore/app/models/__init__.py", line 4, in <module>
    from .base import (
  File "/usr/lib/python3.11/site-packages/pulpcore/app/models/base.py", line 3, in <module>
    from django.contrib.contenttypes.fields import GenericRelation
  File "/usr/lib/python3.11/site-packages/django/contrib/contenttypes/fields.py", line 7, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/usr/lib/python3.11/site-packages/django/contrib/contenttypes/models.py", line 139, in <module>
    class ContentType(models.Model):
  File "/usr/lib/python3.11/site-packages/django/db/models/base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
```

and what got our eye was this line:
```python
File "/usr/lib/python3.11/site-packages/pulpcore/app/wsgi.py", line 14, in <module>
    from pulpcore.app.util import init_domain_metrics_exporter
```

Also, there's already a fix for this in the main branch #5178

**To Reproduce**
Installing using pip and rpm packages.

**Expected behavior**
The application should start without issues

### PR DESCRIPTION
**Pull request by decko**
Fixes #5189

### CODE REVIEW

**Comment by Odilhao** [comment]
I tried locally, and it fixed our 3.49 test.

**Comment by gerrod3** [comment]
We should add a changelog to this so it shows up in the check release script.

**Comment by ggainey** [comment]
> We should add a changelog to this so it shows up in the check release script.

Having a changelog for a commit that isn't a cherry-pick can be a problem for check_release, iirc? (Which begs the question of why this *isn't* just a cherry-pick -x of gerrod's commit?)

**Comment by decko** [comment]
> Having a changelog for a commit that isn't a cherry-pick can be a problem for check_release, iirc? (Which begs the question of why this _isn't_ just a cherry-pick -x of gerrod's commit?)

Totally forgot the cherry-pick :(
Let me add @gerrod3 as the co-author of this.

**Review by ggainey — APPROVED** [review]

**Review by gerrod3 — APPROVED** [review]

**Pull request merged**
