### PR TITLE
Change relative_path from CharField to TextField

### PR DESCRIPTION
**Pull request by fabricio-aguiar**
closes #4544
https://pulp.plan.io/issues/4544

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/en/3.0/nightly/contributing/pull-request-walkthrough.html

### CODE REVIEW

**Comment by daviddavis** [comment]
Did you check other repos? I know for example pulp_file has relative_path:

https://github.com/pulp/pulp_file/blob/master/pulp_file/app/models.py#L26

**Comment by fabricio-aguiar** [comment]
> Did you check other repos? I know for example pulp_file has relative_path:
> 
> https://github.com/pulp/pulp_file/blob/master/pulp_file/app/models.py#L26

No, I haven't, I thought the issue was specific for pulpcore

**Comment by daviddavis** [comment]
I think it would be good to at least file issues for other plugins. I suspect though that pulp_file is the only plugin that has a relative_path.

**Comment by fabricio-aguiar** [comment]
> I think it would be good to at least file issues for other plugins. I suspect though that pulp_file is the only plugin that has a relative_path.

I will check it out and open PR for all plugins that have it

**Pull request merged**
