### PR TITLE
Add Plugin API section to changelog

### PR DESCRIPTION
**Pull request by bmbouter**
https://pulp.plan.io/issues/5628
closes #5628

### CODE REVIEW

**Comment by bmbouter** [comment]
The draft changelog produced was this:

```
3.0.0rc8.dev (2019-10-28)
=========================

REST API
--------

Features
~~~~~~~~

- Change `relative_path` from `CharField` to `TextField`
  `#4544 <https://pulp.plan.io/issues/4544>`_
- Users specify Pulp settings file locaiton and type using `PULP_SETTINGS` environment variable.
  `#5560 <https://pulp.plan.io/issues/5560>`_


Bugfixes
~~~~~~~~

- Raise meaningful error for invalid filters.
  `#4780 <https://pulp.plan.io/issues/4780>`_


Misc
~~~~

- `#5028 <https://pulp.plan.io/issues/5028>`_, `#5353 <https://pulp.plan.io/issues/5353>`_, `#5580 <https://pulp.plan.io/issues/5580>`_, `#5612 <https://pulp.plan.io/issues/5612>`_


Plugin API
----------

Improved Documentation
~~~~~~~~~~~~~~~~~~~~~~

- Add `Plugin API` section to the changelog.
  `#5628 <https://pulp.plan.io/issues/5628>`_


----
```

**Comment by daviddavis** [comment]
This is great! A few thoughts:

* Want to add a .gitkeep to the plugin_api directory?
* We'll need to update Travis to check the plugin_api directory for changelog entries (I think)
* Can you update our contributing docs to specify that changes to the plugin API belong in CHANGES/plugin_api.

**Comment by daviddavis** [comment]
Here is the Travis change that's needed: https://github.com/pulp/plugin_template/pull/133

**Comment by bmbouter** [comment]
I re-applied the plugin template to incorporate that change. Thanks @daviddavis

**Comment by bmbouter** [comment]
@daviddavis I pushed the docs changes, lmk how else I can improve it. These were good ideas.

**Pull request merged**
