### PR TITLE
Fix azure artifacts path download

### PR DESCRIPTION
**Pull request by victorcmsantos**
[noissue]

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

### CODE REVIEW

**Comment by goosemania** [comment]
@victorcmsantos , this PR looks to me like an amend of the commit from the master branch. You modified the existing merged commit, let's not do that.
If it was an attempt to follow those instructions https://github.com/pulp/pulpcore/pull/1135#discussion_r578758177, please make sure you are on your branch called `victor`, after making all the changes, please make sure you are modifying your own commit. and `push -f` to your branch `victor` as well. That will modify the PR you originally opened, and I think we could close this one then. Thanks

**Comment by dralley** [comment]
@victorcmsantos Could you elaborate on what the problem was?

**Comment by dralley** [comment]
If it's broken, could you file an issue (which this PR will fix) so that it's documented?

**Comment by ipanova** [comment]
closed in favour of https://github.com/pulp/pulpcore/pull/1194

**Pull request closed without merging**
