### PR TITLE
Correctly expose the serializer for RepositoryVersion repair

### PR DESCRIPTION
**Pull request by gerrod3**
[noissue]

This also fixes the bindings asking for the wrong arguement.

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

### CODE REVIEW

**Comment by dralley** [comment]
@gerrod3  Has this been encountered in a released version?  Should an issue be filed?

**Comment by gerrod3** [comment]
> @gerrod3 Has this been encountered in a released version? Should an issue be filed?

This clarity issue has been here for a while, but it seems to have no impact on the functionality so I'm unsure if it needs an issue. Even if you supply the incorrect param `base_version` that the API docs say to provide nothing happens as the real param `verify_checksums` has a default value.

The bigger issue is that it makes the bindings for calling repair confusing and I was having a hard time figuring out why it was wrong and we haven't noticed since we don't test repair with the bindings currently. (https://github.com/pulp/pulpcore/blob/main/pulpcore/tests/functional/api/using_plugin/test_repair.py)

**Review by dralley — APPROVED** [review]

**Comment by dralley** [comment]
Only comment, Katello probably uses the bindings for repair, so if actually *changes* the bindings we might want to be thoughtful about how we merge.

**Comment by mdellweg** [comment]
Azure tests seem to be broken today.
And the S3 is a timing issue with another test, supposed to be fixed by https://github.com/pulp/pulpcore/pull/2265/files#diff-ab70ec0b308fb8c0d3b40add15f611d0e4ea32400db7b25db2631c8c70047fb8R115

**Review by bmbouter — CHANGES_REQUESTED** [review]
I think this needs a changelog change.

**Review by bmbouter — APPROVED** [review]
Thank you!

**Pull request merged**
