### PR TITLE
Small import/export improvements

### PR DESCRIPTION
**Pull request by dralley**
Preparation for bigger stuff.  This can be more easily backported as-is.

### CODE REVIEW

**Review by mdellweg — APPROVED** [review]

**Review by ipanova — APPROVED** [review]
can we stick to s/cumulative_hash/global_hash
especially if this is used only in import/export and in export.jsonm file we also have global_hash or else renaming there too so its consistent. Since this would a user visible change, stick to global_hash is my suggestion

**Comment by dralley** [comment]
>can we stick to s/cumulative_hash/global_hash
especially if this is used only in import/export and in export.json file we also have global_hash or else renaming there too so its consistent. Since this would a user visible change, stick to global_hash is my suggestion

Nothing about this is a user-visible change, and I didn't rename the actual variable itself in the export code.  I just though `cumulative_hash` made more sense for the name of the function argument.

**Comment by ipanova** [comment]
my 2c, merge at will

**Comment by dralley** [comment]
The way I think of it is that from the perspective of the utility function, it's just a cumulative hash that you're adding to.  The utility doesn't know anything about the way it's being used so "global" isn't meaningful.  From the perspective of the export code, it's a global hash and is still called as such there.

**Pull request merged**
