### PR TITLE
Update Links

### PR DESCRIPTION
**Pull request by amayer5125**
Change 3.0/nightly links to link to current docs
Use https for pulpproject.org links

### CODE REVIEW

**Comment by bmbouter** [comment]
Thank you for submitting these fixes. Can you squash your commits into one, and add a `[noissue]` into your commit message. Then Travis should pass. See https://docs.pulpproject.org/contributing/git.html#commit-message for some more info.

**Comment by amayer5125** [comment]
Requested changes have been made.

**Comment by bmbouter** [comment]
Sorry about this conflict! I was waiting for Travis to merge when another PR was merged. :/ Would you mind resolving?

**Comment by amayer5125** [comment]
Conflict has been resolved.

**Pull request merged**
