### PR TITLE
Fix installing dev_requirements.txt breaking pulpcore

### PR DESCRIPTION
**Pull request by mikedep333**
by limiting django-extensions to versions <3.2.0.

fixes: #3019

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

### CODE REVIEW

**Review by bmbouter — APPROVED** [review]
This looks fine to me. It's dev_requirements anyway so I don't see this affecting users.

**Comment by dralley** [comment]
@mikedep333 This is made against the 3.9 branch, intentional?  If yes, you possibly can't use github issue links, the branch is still configured to use redmine.

**Comment by mikedep333** [comment]
> @mikedep333 This is made against the 3.9 branch, intentional? If yes, you possibly can't use github issue links, the branch is still configured to use redmine.

Yes, it is intentional.

I modified the commit message to be '[noissue]'

**Comment by mikedep333** [comment]
@pulp/core The 3.9 CI is broken in multiple ways. Can you please force merge?

**Pull request merged**
