### PR TITLE
Raise an exception for invalid data for repository/repair/

### PR DESCRIPTION
**Pull request by lubosmj**
[noissue]

ref #3646

### CODE REVIEW

**Comment by gerrod3** [comment]
Was this change supposed to be included with https://github.com/pulp/pulpcore/pull/3646/?

**Comment by lubosmj** [comment]
It could be included, but it was not a must. I am fine with reverting the referenced commit. We can include this change there as well.

**Comment by gerrod3** [comment]
No, I'm just wondering if this also needs a changelog. To me it seems like this fix also falls under the last PR's changelog.

**Comment by lubosmj** [comment]
I have referenced the issue from the commit description. Let's say that this is satisfactory.

**Review by gerrod3 — APPROVED** [review]

**Pull request merged**
