### PR TITLE
Merge ContentUnassociation stage into the ContentAssociation stage

### PR DESCRIPTION
**Pull request by dralley**
ContentUnassociation doesn't really need to be a separate stage, and
making it one breaks the expectations of the "pipeline" by changing the
semantics of what goes into and out of the queues.

closes: #8827
https://pulp.plan.io/issues/8827

### CODE REVIEW

**Review by mdellweg — CHANGES_REQUESTED** [review]
I really like this change.

However, i think we cannot simply remove the `ContentUnassociation` stage and change the signature of the `ContentAssociation` stage.

To adhere to the deprecation policy, i suggest to:
* Deprecate the `ContentUnassociation` stage
* Make the (new) `mirror` flag in the `ContentAssociation` stage default to `False`.

Sadly we would need to keep the bad interface of passing on the queryset to the deprecated `ContentUnassociation` stage for a release longer.

Maybe I can be convinced, that these two stages de facto never were part of the plugin api. Is there a way, we can move them out of the pulpcore/plugin directory in that case?

**Comment by dralley** [comment]
> To adhere to the deprecation policy, i suggest to:
> * Deprecate the ContentUnassociation stage

@mdellweg We did do that :) 

https://pulp.plan.io/issues/8635
https://github.com/pulp/pulpcore/pull/1302

> Maybe I can be convinced, that these two stages de facto never were part of the plugin api. Is there a way, we can move them out of the pulpcore/plugin directory in that case?

FWIW, this is essentially true also, so even this is more of an "abundance of caution".  No plugin uses these directly and it's very difficult to actually do so, the standard API that plugins that create their own pipelines use can't do it because they're injected at the very end of the pipeline by pulpcore.

**Review by mdellweg — APPROVED** [review]
I was convinced. ;)

What do you still think about not having them part of the pulpcore.plugin interface?
Or maybe guard by adding "_" in the name?

**Comment by bmbouter** [comment]
I know in practice plugins don't use this, but to be totally technical, they could.

My opinion is that all the parts of the stages API should be available in `pulpcore.plugin`.

**Comment by dralley** [comment]
They could but they would need to patch / override `DeclarativeVersion` itself to do so.

**Comment by mdellweg** [comment]
> I know in practice plugins don't use this, but to be totally technical, they could.
> 
> My opinion is that all the parts of the stages API should be available in `pulpcore.plugin`.

That means (de jure ; not de facto) we can never change the interface of anything in the stages api (even if never used directly by a plugin) in a backwards incompatible way without properly deprecating for a release.

**Comment by bmbouter** [comment]
I'm being pedantic here because I don't know anyone who does this, but plugin writers are allowed to construct their own pipelines without `DeclarativeVersion`.

**Comment by dralley** [comment]
@bmbouter Yes but that mechanism doesn't allow you to influence this part of the pipeline

https://github.com/pulp/pulpcore/blob/master/pulpcore/plugin/stages/declarative_version.py#L143-L147

**Comment by dralley** [comment]
The migration plugin does do that, but they don't use the `Content*Association` stages at all.  They just create the content.

**Review by bmbouter — APPROVED** [review]
Thanks @dralley !

**Pull request merged**
