### PR TITLE
Fix URL encoding issue in HttpDownloader to handle special characters

### LINKED ISSUE #5686: pulp_file fails to sync file repos literally containing URL encoding strings like %3a in a file name
### Version
Tested using `python3.11-pulp-file-1.15.1` on a Katello instance

### Describe the bug
If a file in a file repo literally contains for example `%3a` in the filename, then this repo cannot be synced to pulp_file, because the download URL unparses the `%3a` to `:` and runs into a 404, e.g:
```
404, message='Not Found', url=URL('http://my-file-server/pub/file_repo/stupid-file-name-:-blub')
```

### To Reproduce
I manually create a local file repo as follows:
```
mkdir file_repo
touch file_repo/stupid-file-name-%3a-blub
echo "blub" > file_repo/stupid-file-name-%3a-blub
bash make_pulp_manifest.sh
```
Here `make_pulp_manifest.sh` is:
```
TARGET_PATH=file_repo

for TARGET_FILE in "${TARGET_PATH}/"*
do
  FILE="$(basename "${TARGET_FILE}")"
  SHA256="$(sha256sum "${TARGET_FILE}" | cut -d ' ' -f 1)"
  SIZE="$(stat --printf="%s" "${TARGET_FILE}")"
  echo "${FILE},${SHA256},${SIZE}" >> ${TARGET_PATH}/PULP_MANIFEST
done
```
Feel free to create the PULP_MANIFEST file any other way!

Now serve this file repo somewhere and sync it to pulp_file and observe the sync error.
```
404, message='Not Found', url=URL('http://my-file-server/pub/file_repo/stupid-file-name-:-blub')
```

### Expected behavior

Sync succeeds. Not sure how difficult it is to differentiate between a URL that contains URL encodings that should be converted and one like this case where the URL encoding string is literally part of the filename/path.

### Additional context

The issue was originally discovered via the real world use case of trying to synchronize a mounted Ubuntu 22.04 iso into pulp_file. Example "problem files" from the mounted Ubuntu iso:
```
# ls -l /var/www/html/pub/ubuntu22/22.04-x86_64/pool/main/o/openssh/
total 468
-r--r--r--. 1 root root 435336 Jan  3  2024 openssh-server_1%3a8.9p1-3ubuntu0.6_amd64.deb
-r--r--r--. 1 root root  38716 Jan  3  2024 openssh-sftp-server_1%3a8.9p1-3ubuntu0.6_amd6
```

### PR DESCRIPTION
**Pull request by hstct**
closes #5686

### CODE REVIEW

**Comment by lubosmj** [comment]
Please, write a changelog message named after the issue number, like so: CHANGES/5686.bugfix.

https://pulpproject.org/pulpcore/docs/dev/tutorials/quickstart/?h=changelog#3-update-the-changelog-entry

**Comment by hstct** [comment]
> Please, write a changelog message named after the issue number, like so: CHANGES/5686.bugfix.
> 
> https://pulpproject.org/pulpcore/docs/dev/tutorials/quickstart/?h=changelog#3-update-the-changelog-entry

Ah yea, sorry it was late yesterday xD

**Comment by hstct** [comment]
For additional context:

The issue we encountered wasn’t just that the filename contained `%3a`, which was then decoded to `:`. The file couldn’t be found on the server, regardless of whether `%3`a or `:` was used. The main problem was that the `%` in the filename was double-encoded, resulting in `%253a` as the actual filename.

**Comment by hstct** [comment]
Added some tests for this as well.

**Comment by hstct** [comment]
idk why the test is failing on github :cry:

**Comment by git-hyagi** [comment]
hi @hstct 

I was checking this error, and I think it might be related to the way aiohttp server is parsing the request (but it is just a guess, I could not make it work yet):
https://github.com/pulp/pulpcore/blob/e360a133406a2e4e57305369ff27337ecf6af804/pulpcore/pytest_plugin.py#L322-L328

I will do more tests and let you know if I find something.

**Comment by git-hyagi** [comment]
I managed to make the test work by modifying the [pulpcore/pytest_plugin.py](https://github.com/pulp/pulpcore/blob/e360a133406a2e4e57305369ff27337ecf6af804/pulpcore/pytest_plugin.py#L321-L328) file with:
```
@pytest.fixture
def gen_fixture_server(gen_threaded_aiohttp_server):
    def _gen_fixture_server(fixtures_root, ssl_ctx):
        app = web.Application(middlewares=[_aiohttp_request_middleware])
        call_record = add_recording_route(app, fixtures_root)
        return gen_threaded_aiohttp_server(app, ssl_ctx, call_record)

    yield _gen_fixture_server


@web.middleware
async def _aiohttp_request_middleware(request,handler):
    unquoted_url = urllib.parse.unquote(request.url.human_repr())
    url = urllib.parse.urlparse(unquoted_url)
    response = await handler(request.clone(rel_url=url.path))
    return response
```

but I don't know the impact of this change in the other tests, or if this could be even considered a viable "solution".

**Comment by hstct** [comment]
hi @git-hyagi thanks for the help!

As far as I can tell and this has been the whole problem with this issue in general is that it always is dependent on how the web server is serving the files, whether or not it will encode `%3a` to `%253a` or read it as an encoded `:`. So your approach really did help out here. I've been running tests for pulp_rpm, pulpcore, and pulp_deb locally and they seem to work fine. However I doubt that there are many tests that purposefully use problematic filenames. And that is what it is in the end, files having problematic names with special characters that get encoded when served online. So this is a workaround to make it more robust but I also can't tell if this is sufficient.

**Review by git-hyagi — APPROVED** [review]
Thank you for the contribution!
LGTM

**Review by gerrod3 — APPROVED** [review]
Nice testing!

**Comment by quba42** [comment]
I am afraid we may have shot ourselves in the foot here. Our internal integration  tests revealed that while this fixes what we set out to fix, it broke the far more important use case of "download URL's with special characters in them".

I have just verified this using latest pulpcore main branch in oci-env. I tried syncing a fairly standard APT repo, which failed because Pulp tried to download `adduser_3.118%252Bdeb11u1_all.deb` instead of `adduser_3.118+deb11u1_all.deb`.

I suggest we revert this PR for now, until we can figure out a better approach. Unfortunately I fear there may be no good way to make the down-loader robust for both use cases.

**Pull request merged**
