### PR TITLE
Returned content_guards API to correct contentguards.

### PR DESCRIPTION
**Pull request by ggainey**
fixes #8283
[nocoverage]

### CODE REVIEW

**Review by mdellweg — APPROVED** [review]
I feel guilty. Thank you for finding it!

**Review by ipanova — APPROVED** [review]

**Comment by ggainey** [comment]
Don't merge yet, I want to add a test to catch this!

**Comment by mdellweg** [comment]
I thought we had a test. We just didn't look at it.

**Comment by ggainey** [comment]
> I thought we had a test. We just didn't look at it.

pulp-certguard has a test - pulpcore, where the change happened, doesn't. If there'd been a test in pulpcore to test "connect a content-guard to a distribution", it would have failed when you submitted the PR and you'd have caught this before it got merged.

**Comment by mdellweg** [comment]
I thought, the pulpcertguard tests are part of pulpcore's ci.

**Comment by ggainey** [comment]
> I thought, the pulpcertguard tests are part of pulpcore's ci.

If they were, your PR would never have passed, yeah?

**Review by bmbouter — APPROVED** [review]
Thank you!

**Comment by bmbouter** [comment]
I see three approvals, merging!

**Pull request merged**
