### PR TITLE
Log telemetry data in debug instead of info

### PR DESCRIPTION
**Pull request by mdellweg**
[noissue]

### CODE REVIEW

**Review by ipanova — COMMENTED** [review]
I don't think we can log it to debug because of the data we collect and transparency. 
In the end of the it runs only once a day so it will not spam much.

**Comment by mdellweg** [comment]
This piece of data, i believe is going to be very big. So i would rather keep it out of the "normal" logs.

**Comment by ipanova** [comment]
> This piece of data, i believe is going to be very big. So i would rather keep it out of the "normal" logs.

https://github.com/pulp/pulpcore/pull/3116/files#diff-15f48b1c68b7af454cd98e0bf19214298ad0a7bb1fa3cd0fda8e5e8e51d98033R122

**Comment by ipanova** [comment]
Regardless of the size i still think we should be transparent about the fact that we sent user's data.

**Comment by bmbouter** [comment]
I agree that logging this is an important point of transparency with our users.

**Pull request closed without merging**
