### PR TITLE
Disable docs publishing for this branch.

### PR DESCRIPTION
**Pull request by decko**
[noissue]

### CODE REVIEW

**Review by mdellweg — COMMENTED** [review]
This looks about right, but we are still building (and maybe failing to) the docs this way.

**Comment by decko** [comment]
> This looks about right, but we are still building (and maybe failing to) the docs this way.

I don't think so.
https://github.com/pulp/pulpcore/pull/5393/files#diff-551d1fcf87f78cc3bc18a7b332a4dc5d8773a512062df881c5aba28a6f5c48d7L113-L126

**Comment by pedro-psb** [comment]
It should also be disabled [here](https://github.com/pulp/pulpcore/blob/865e5c9d6b31d594327d256453489c89f5f27fa1/template_config.yml#L109), which should disable building it on the CI as well.

**Comment by decko** [comment]
> It should also be disabled [here](https://github.com/pulp/pulpcore/blob/865e5c9d6b31d594327d256453489c89f5f27fa1/template_config.yml#L109), which should disable building it on the CI as well.
> 
> Edit: or maybe this doesn't make a difference for this branch? I'm not sure

Cool! I can do that.

**Review by dralley — APPROVED** [review]

**Pull request merged**
