### PR TITLE
Update requirements for dependencies

### PR DESCRIPTION
**Pull request by daviddavis**
Also bump gunicorn version requirement.

[noissue]

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/en/3.0/nightly/contributing/pull-request-walkthrough.html

### CODE REVIEW

**Comment by evgeni** [comment]
:+1: this should fix *my* issues on EL7.

**Comment by daviddavis** [comment]
@mikedep333 will this cause any problems with installing Pulp? This change will compile psycopg2 and it requires some dependencies like psql-devel I believe.

**Comment by evgeni** [comment]
`postgresql-devel` on CentOS7.

**Comment by mikedep333** [comment]
@daviddavis @evgeni [It requires](http://initd.org/psycopg/docs/install.html#build-prerequisites) (on CentOS7, and similar Fedora names):
- postgresql-devel
- postgresql (clients only. for /usr/bin/pg_config)
- python3-devel (I'm fairly certain this is needed for venvs)

I think these are  reasonable RPM requirements to maintain a clean venv without system-wide packages. This change should be made to https://github.com/pulp/pulp_rpm_prerequisites

The alternative would be to use the system packages like python3-psycopg2, but then system-wide packages would always be necessary within the venv.

**Comment by evgeni** [comment]
The linked repo says it's only for pulp-rpm, not for pulpcore?

**Comment by mikedep333** [comment]
@evgeni Correct. Because pulpcore does not need any new RPMs currently.

**Comment by mikedep333** [comment]
@evgeni My bad. Fixing my comment now.

**Pull request merged**
