### PR TITLE
3.14.1 backports

### PR DESCRIPTION
**Pull request by daviddavis**
Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/contributing/pull-request-walkthrough.html

### CODE REVIEW

**Comment by daviddavis** [comment]
@bmbouter here were the commands I ran:

```
git fetch
git checkout 3.14
git checkout -b 3.14-release
.ci/scripts/cherrypick.sh f52ba80e4 9008 9025
.ci/scripts/cherrypick.sh e4b1724 9003 9015
```

**Comment by bmbouter** [comment]
I ran:

```
git fetch pulp
git checkout pulp/3.14
git checkout -b the-branch-name
./cherrypick.sh e4b17247d30b85841e5065d745a1fbb219a58cec 9003 9015
./cherrypick.sh f52ba80e41ebbb532a87b6aa50821911a01348ff 9008 9025
```

**Comment by daviddavis** [comment]
Ah yea, I see the problem. You have to run it from the root dir or else you get:

```
find: ‘CHANGES’: No such file or directory
```

Let me open a fix.

**Review by bmbouter — APPROVED** [review]
Thank you!

**Pull request merged**
