### PR TITLE
Fix a bug where workers miss notifications

### LINKED ISSUE #2506: All workers idle while a task is pending
**Version**
At least 3.14.14 used in katello

**Describe the bug**
Workers can all enter sleep state and miss the wakeup notification leading to pending tasks while all workers idle. Dispatching a new tasks unfreezes the system again.

**To Reproduce**
https://bugzilla.redhat.com/show_bug.cgi?id=2050440

**Expected behavior**
At least one worker is expected to pick up the next pending task.

**Additional context**
https://bugzilla.redhat.com/show_bug.cgi?id=2050440

### PR DESCRIPTION
**Pull request by mdellweg**
fixes #2506

### CODE REVIEW

**Comment by mdellweg** [comment]
This is probably the easiest fix for this situation. But maybe we can do better.

**Comment by dkliban** [comment]
@mdellweg, I don't understand this change. Can you please explain?

**Comment by mdellweg** [comment]
> @mdellweg, I don't understand this change. Can you please explain?

The async postgres notifications are fetched on any database query, not only `connection.poll()` so it may happen that e.g. the saving of the heartbeat acidentally fetched a notification into the `connection.notifies` list, leaving the file descriptor invisible to `select`. Therefore we cannot rely on the fact that all notifications will trigger the connection to pop up in the result of `select`, And we need to check for the existence of notifications outside of the `if connection in r:` condition.

**Comment by mdellweg** [comment]
I'll revise the notification handling in the loop once more.

**Review by dkliban — APPROVED** [review]

**Review by bmbouter — APPROVED** [review]
Thank you!

**Comment by mdellweg** [comment]
I'll take care of the failed cherry-picks.

**Comment by mdellweg** [comment]
https://github.com/pulp/pulpcore/pull/2521

**Comment by mdellweg** [comment]
3.15: https://github.com/pulp/pulpcore/pull/2522

**Comment by mdellweg** [comment]
3.14: https://github.com/pulp/pulpcore/pull/2523

**Pull request merged**
