### PR TITLE
Re-orders migrations 43 and 44

### PR DESCRIPTION
**Pull request by dkliban**
This will allow cherry-picking migration 43 (old 44) into 3.6.1

[noissue]

### CODE REVIEW

**Comment by mdellweg** [comment]
Somehow, I am not convinced, this is a good idea. Are we breaking upgrading to the next major release if we generate a new migration with the cherry pick?

**Comment by dralley** [comment]
Not unless we've already released one of those migrations, which I don't *think* we have.

However, I'm not really thrilled about this either.

**Comment by dkliban** [comment]
We have not released these migrations. They are only present on the master branch. I am re-ordering them on the master branch and then plan to cherry-pick this commit to the 3.6 branch.

**Comment by bmbouter** [comment]
I am not in favor of reordering master for a z-release. I recommend not shipping migrations in z-stream and closing this pr. I put this as a discussion point for Sept 4th open floor also.

**Comment by dkliban** [comment]
It is not critical to ship this bug fix with 3.6.1. Closing this PR.

**Pull request closed without merging**
