### PR TITLE
Export EncryptedTextField in the plugin api

### LINKED ISSUE #3157: Export the EncryptedTextField in the plugin API

### PR DESCRIPTION
**Pull request by mdellweg**
fixes #3157

### CODE REVIEW

**Review by ggainey — APPROVED** [review]
lg2m

**Comment by bmbouter** [comment]
@mdellweg this looks fine, but what will use it in 3.21?

**Comment by mdellweg** [comment]
pulp_ansible is going to use that type of field.

**Review by bmbouter — APPROVED** [review]
Thanks!

**Pull request merged**
