### PR TITLE
Removing non_fatal_errors from Task model

### PR DESCRIPTION
**Pull request by fabricio-aguiar**
closes #5537
https://pulp.plan.io/issues/5537

Please be sure you have read our documentation on creating PRs:
https://docs.pulpproject.org/en/3.0/nightly/contributing/pull-request-walkthrough.html

### CODE REVIEW

**Comment by bmbouter** [comment]
I think it also needs to be removed from here: https://github.com/pulp/pulpcore-plugin/blob/0ddad70610fe364e62f984473a2e8941c24f40c7/docs/reference/error-handling.rst#L10

**Comment by fabricio-aguiar** [comment]
> I think it also needs to be removed from here: https://github.com/pulp/pulpcore-plugin/blob/0ddad70610fe364e62f984473a2e8941c24f40c7/docs/reference/error-handling.rst#L10

https://github.com/pulp/pulpcore-plugin/pull/141

**Comment by bmbouter** [comment]
code-wise this all looks good. Can you also handle the necessary references from here also? https://github.com/pulp/pulpcore/search?utf8=%E2%9C%93&q=fatal&type=

**Comment by bmbouter** [comment]
It might just be that 1 docs entry.

**Comment by fabricio-aguiar** [comment]
> It might just be that 1 docs entry.

@bmbouter from what I see, the doc that you mentioned is about `fatal` errors, locally with `ctrl+shift+F` I can't find any more `non_fatal_errors`

**Comment by bmbouter** [comment]
@fabricio-aguiar I agree, I misread the docs.

**Pull request merged**
