### PR TITLE
Retry downloads on checksum mismatch

### PR DESCRIPTION
**Pull request by dralley**
closes: #9667
https://pulp.plan.io/issues/9667

### CODE REVIEW

**Comment by bmbouter** [comment]
Apologies I didn't see this until now. Small nitpick, this change I think is definitly a bugfix or feature, not `misc`. It would be good to adjust that if you agree.

Bigger question: I'm a little unsure if if this is what we want, but maybe it is? I gotta think it over. The case I worry about is when the metadata advertises a checksum/digest and yet the binary data is different. Would that ever happen? I suppose not? Can you think of a time when binary data would mutate on server sides?

**Comment by dralley** [comment]
@bmbouter The problem is that in this case it wasn't repeatable, it would just occasionally happen for different packages.  I kinda hate the CDN.

That *can* happen but in that case it's 100% definitely a metadata issue.

**Comment by ipanova** [comment]
I am ok to expose this as bugfix for the sake of visibility for users.

**Comment by bmbouter** [comment]
I think if we make it a bugfix I'm +1. Thanks

**Comment by dralley** [comment]
@fao89 We can manually cherrypick from my 3.14-cherrypicks PR (but let's review and merge that first)

**Comment by fao89** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2033174

**Pull request merged**
