### PR TITLE
Revert "pulpcore-manager defaults to '/etc/pulp/settings.py'"

### PR DESCRIPTION
**Pull request by gerrod3**
Reverts pulp/pulpcore#2401

### CODE REVIEW

**Review by mdellweg — APPROVED** [review]
Based on the matrix discussion, this seems to be what we need to do.

**Review by bmbouter — APPROVED** [review]
Thank you, I appreciate it.

**Comment by bmbouter** [comment]
@fao89 how did you resolve this problem with your backports?

**Comment by fao89** [comment]
> @fao89 how did you resolve this problem with your reverts?

I edited the commit message

**Pull request merged**
